const areaMeta = {
  "JVC": {
    label: "JVC",
    community: "Jumeirah Village Circle",
    lat: 25.0562,
    lng: 55.2090,
    sparkline: [3, 4, 4, 5, 6, 8, 9],
  },
  "Al Barsha": {
    label: "Al Barsha",
    community: "Al Barsha South",
    lat: 25.1124,
    lng: 55.2028,
    sparkline: [2, 3, 4, 4, 5, 5, 6],
  },
  "Dubai Marina": {
    label: "Dubai Marina",
    community: "JBR",
    lat: 25.0800,
    lng: 55.1403,
    sparkline: [4, 5, 5, 7, 7, 8, 10],
  },
  "Business Bay": {
    label: "Business Bay",
    community: "Executive Towers",
    lat: 25.1866,
    lng: 55.2645,
    sparkline: [3, 3, 5, 6, 7, 8, 8],
  },
  "Mirdif": {
    label: "Mirdif",
    community: "Uptown Mirdif",
    lat: 25.2205,
    lng: 55.4243,
    sparkline: [2, 2, 3, 4, 5, 6, 7],
  },
  "Town Square": {
    label: "Town Square",
    community: "Hayat Townhouses",
    lat: 25.0300,
    lng: 55.2650,
    sparkline: [1, 2, 3, 3, 5, 5, 6],
  },
  "Motor City": {
    label: "Motor City",
    community: "Dubai Sports City",
    lat: 25.0470,
    lng: 55.2438,
    sparkline: [2, 3, 3, 4, 5, 6, 6],
  },
  "Dubai Hills": {
    label: "Dubai Hills",
    community: "Park Heights",
    lat: 25.1117,
    lng: 55.2541,
    sparkline: [2, 3, 4, 5, 5, 7, 8],
  },
  "DIFC": {
    label: "DIFC",
    community: "Index Tower",
    lat: 25.2114,
    lng: 55.2796,
    sparkline: [3, 4, 4, 5, 6, 7, 7],
  },
  "Jumeirah": {
    label: "Jumeirah",
    community: "Jumeirah 2",
    lat: 25.2146,
    lng: 55.2525,
    sparkline: [1, 2, 3, 4, 4, 6, 7],
  },
};

const scanTimes = [
  "2026-03-07T03:48:00+04:00",
  "2026-03-07T03:56:00+04:00",
  "2026-03-07T04:02:00+04:00",
  "2026-03-07T04:08:00+04:00",
  "2026-03-07T04:12:00+04:00",
];

function buildHistory(originalPrice, currentPrice) {
  const midpointOne = Math.round(originalPrice - (originalPrice - currentPrice) * 0.22);
  const midpointTwo = Math.round(originalPrice - (originalPrice - currentPrice) * 0.48);
  const midpointThree = Math.round(originalPrice - (originalPrice - currentPrice) * 0.78);

  return [
    { date: "2026-02-03", price: originalPrice },
    { date: "2026-02-14", price: midpointOne },
    { date: "2026-02-23", price: midpointTwo },
    { date: "2026-03-02", price: midpointThree },
    { date: "2026-03-07", price: currentPrice },
  ];
}

function createListing(config, index) {
  const { lat, lng } = areaMeta[config.area];
  const dropAmount = config.originalPrice - config.currentPrice;
  const dropPercent = (dropAmount / config.originalPrice) * 100;

  return {
    id: config.id,
    title: config.title,
    area: config.area,
    community: config.community,
    type: config.type,
    bedrooms: config.bedrooms,
    sqft: config.sqft,
    originalPrice: config.originalPrice,
    currentPrice: config.currentPrice,
    dropAmount,
    dropPercent: Number(dropPercent.toFixed(1)),
    daysOnMarket: config.daysOnMarket,
    droppedYesterday: config.droppedYesterday,
    validated: config.validated ?? true,
    expatArea: config.expatArea ?? true,
    familyFriendly: config.familyFriendly ?? false,
    lat,
    lng,
    priceHistory: buildHistory(config.originalPrice, config.currentPrice),
    lastScanned: config.lastScanned ?? scanTimes[index % scanTimes.length],
  };
}

const listingConfigs = [
  {
    id: "jvc-1",
    title: "1BR | JVC | Balcony + Pool Deck",
    area: "JVC",
    community: "Bloom Towers",
    type: "apartment",
    bedrooms: 1,
    sqft: 760,
    originalPrice: 97000,
    currentPrice: 82000,
    daysOnMarket: 14,
    droppedYesterday: true,
    expatArea: true,
  },
  {
    id: "jvc-2",
    title: "2BR | JVC | Park View",
    area: "JVC",
    community: "Belgravia Heights",
    type: "apartment",
    bedrooms: 2,
    sqft: 1140,
    originalPrice: 118000,
    currentPrice: 105000,
    daysOnMarket: 19,
    droppedYesterday: false,
    expatArea: true,
  },
  {
    id: "jvc-3",
    title: "3BR Villa | JVC | Corner Plot",
    area: "JVC",
    community: "Nakheel Villas",
    type: "villa",
    bedrooms: 3,
    sqft: 2280,
    originalPrice: 190000,
    currentPrice: 168000,
    daysOnMarket: 28,
    droppedYesterday: true,
    expatArea: true,
    familyFriendly: true,
  },
  {
    id: "albarsha-1",
    title: "2BR | Al Barsha | School Access",
    area: "Al Barsha",
    community: "Al Barsha South",
    type: "apartment",
    bedrooms: 2,
    sqft: 1325,
    originalPrice: 145000,
    currentPrice: 128000,
    daysOnMarket: 11,
    droppedYesterday: true,
    expatArea: true,
    familyFriendly: true,
  },
  {
    id: "albarsha-2",
    title: "4BR Villa | Al Barsha | Private Garden",
    area: "Al Barsha",
    community: "Al Barsha 2",
    type: "villa",
    bedrooms: 4,
    sqft: 3250,
    originalPrice: 228000,
    currentPrice: 205000,
    daysOnMarket: 21,
    droppedYesterday: false,
    expatArea: true,
    familyFriendly: true,
  },
  {
    id: "marina-1",
    title: "2BR | Dubai Marina | Sea View",
    area: "Dubai Marina",
    community: "Marina Gate",
    type: "apartment",
    bedrooms: 2,
    sqft: 1210,
    originalPrice: 214000,
    currentPrice: 178000,
    daysOnMarket: 16,
    droppedYesterday: true,
    expatArea: true,
  },
  {
    id: "marina-2",
    title: "3BR | JBR | Full Marina Exposure",
    area: "Dubai Marina",
    community: "JBR",
    type: "apartment",
    bedrooms: 3,
    sqft: 1765,
    originalPrice: 255000,
    currentPrice: 224000,
    daysOnMarket: 24,
    droppedYesterday: false,
    expatArea: true,
  },
  {
    id: "marina-3",
    title: "1BR | Marina | Furnished Investor Unit",
    area: "Dubai Marina",
    community: "Sparkle Towers",
    type: "apartment",
    bedrooms: 1,
    sqft: 790,
    originalPrice: 165000,
    currentPrice: 149000,
    daysOnMarket: 9,
    droppedYesterday: true,
    expatArea: true,
  },
  {
    id: "businessbay-1",
    title: "1BR | Business Bay | Canal View",
    area: "Business Bay",
    community: "Executive Towers",
    type: "apartment",
    bedrooms: 1,
    sqft: 860,
    originalPrice: 180000,
    currentPrice: 156000,
    daysOnMarket: 13,
    droppedYesterday: true,
    expatArea: true,
  },
  {
    id: "businessbay-2",
    title: "2BR | Business Bay | Office District Edge",
    area: "Business Bay",
    community: "Aykon City",
    type: "apartment",
    bedrooms: 2,
    sqft: 1180,
    originalPrice: 149000,
    currentPrice: 132000,
    daysOnMarket: 17,
    droppedYesterday: false,
    expatArea: true,
  },
  {
    id: "businessbay-3",
    title: "Studio | Business Bay | High Yield",
    area: "Business Bay",
    community: "DAMAC Maison",
    type: "apartment",
    bedrooms: 0,
    sqft: 510,
    originalPrice: 118000,
    currentPrice: 104000,
    daysOnMarket: 8,
    droppedYesterday: true,
    expatArea: true,
  },
  {
    id: "mirdif-1",
    title: "3BR Villa | Mirdif | Family Compound",
    area: "Mirdif",
    community: "Shorooq",
    type: "villa",
    bedrooms: 3,
    sqft: 2810,
    originalPrice: 165000,
    currentPrice: 142000,
    daysOnMarket: 26,
    droppedYesterday: false,
    expatArea: true,
    familyFriendly: true,
  },
  {
    id: "mirdif-2",
    title: "2BR Villa | Mirdif | Close To Park",
    area: "Mirdif",
    community: "Uptown Mirdif",
    type: "villa",
    bedrooms: 2,
    sqft: 1920,
    originalPrice: 130000,
    currentPrice: 118000,
    daysOnMarket: 15,
    droppedYesterday: false,
    expatArea: true,
    familyFriendly: true,
  },
  {
    id: "mirdif-3",
    title: "1BR | Mirdif | Courtyard Apartment",
    area: "Mirdif",
    community: "Mirdif Hills",
    type: "apartment",
    bedrooms: 1,
    sqft: 875,
    originalPrice: 111000,
    currentPrice: 98000,
    daysOnMarket: 10,
    droppedYesterday: true,
    expatArea: true,
    familyFriendly: true,
  },
  {
    id: "townsquare-1",
    title: "1BR | Town Square | Boulevard Facing",
    area: "Town Square",
    community: "Rawda Apartments",
    type: "apartment",
    bedrooms: 1,
    sqft: 690,
    originalPrice: 99000,
    currentPrice: 86000,
    daysOnMarket: 18,
    droppedYesterday: true,
    expatArea: true,
  },
  {
    id: "townsquare-2",
    title: "3BR Villa | Town Square | Cluster Pool",
    area: "Town Square",
    community: "Hayat Townhouses",
    type: "villa",
    bedrooms: 3,
    sqft: 2215,
    originalPrice: 171000,
    currentPrice: 152000,
    daysOnMarket: 20,
    droppedYesterday: false,
    expatArea: true,
    familyFriendly: true,
  },
  {
    id: "townsquare-3",
    title: "2BR | Town Square | Investor Holdout",
    area: "Town Square",
    community: "Zahra Breeze",
    type: "apartment",
    bedrooms: 2,
    sqft: 1045,
    originalPrice: 126000,
    currentPrice: 111000,
    daysOnMarket: 12,
    droppedYesterday: true,
    expatArea: true,
  },
  {
    id: "motorcity-1",
    title: "1BR | Motor City | Green Community Edge",
    area: "Motor City",
    community: "Sherlock Circus",
    type: "apartment",
    bedrooms: 1,
    sqft: 930,
    originalPrice: 108000,
    currentPrice: 94000,
    daysOnMarket: 23,
    droppedYesterday: false,
    expatArea: true,
  },
  {
    id: "motorcity-2",
    title: "2BR | Sports City | Golf Course View",
    area: "Motor City",
    community: "Dubai Sports City",
    type: "apartment",
    bedrooms: 2,
    sqft: 1220,
    originalPrice: 115000,
    currentPrice: 103000,
    daysOnMarket: 14,
    droppedYesterday: true,
    expatArea: true,
  },
  {
    id: "motorcity-3",
    title: "3BR Villa | Motor City | Quiet Courtyard",
    area: "Motor City",
    community: "Green Community Motor City",
    type: "villa",
    bedrooms: 3,
    sqft: 2460,
    originalPrice: 192000,
    currentPrice: 171000,
    daysOnMarket: 22,
    droppedYesterday: false,
    expatArea: true,
    familyFriendly: true,
  },
  {
    id: "dubaihills-1",
    title: "2BR | Dubai Hills | Park Access",
    area: "Dubai Hills",
    community: "Park Heights",
    type: "apartment",
    bedrooms: 2,
    sqft: 1290,
    originalPrice: 272000,
    currentPrice: 238000,
    daysOnMarket: 12,
    droppedYesterday: true,
    expatArea: true,
  },
  {
    id: "dubaihills-2",
    title: "4BR Villa | Dubai Hills | Single Row",
    area: "Dubai Hills",
    community: "Maple",
    type: "villa",
    bedrooms: 4,
    sqft: 2980,
    originalPrice: 320000,
    currentPrice: 289000,
    daysOnMarket: 29,
    droppedYesterday: false,
    expatArea: true,
    familyFriendly: true,
  },
  {
    id: "dubaihills-3",
    title: "3BR Villa | Dubai Hills | Near Mall",
    area: "Dubai Hills",
    community: "Sidra Villas",
    type: "villa",
    bedrooms: 3,
    sqft: 2740,
    originalPrice: 308000,
    currentPrice: 276000,
    daysOnMarket: 18,
    droppedYesterday: true,
    expatArea: true,
    familyFriendly: true,
  },
  {
    id: "difc-1",
    title: "1BR | DIFC | Walk To Gate Avenue",
    area: "DIFC",
    community: "Park Towers",
    type: "apartment",
    bedrooms: 1,
    sqft: 810,
    originalPrice: 225000,
    currentPrice: 198000,
    daysOnMarket: 16,
    droppedYesterday: true,
    expatArea: true,
  },
  {
    id: "difc-2",
    title: "2BR | DIFC | Index Tower Exposure",
    area: "DIFC",
    community: "Index Tower",
    type: "apartment",
    bedrooms: 2,
    sqft: 1360,
    originalPrice: 286000,
    currentPrice: 245000,
    daysOnMarket: 20,
    droppedYesterday: false,
    expatArea: true,
  },
  {
    id: "difc-3",
    title: "Studio | DIFC | Compact Executive Unit",
    area: "DIFC",
    community: "Sky Gardens",
    type: "apartment",
    bedrooms: 0,
    sqft: 505,
    originalPrice: 190000,
    currentPrice: 173000,
    daysOnMarket: 7,
    droppedYesterday: true,
    expatArea: true,
  },
  {
    id: "jumeirah-1",
    title: "4BR Villa | Jumeirah | Walk To Beach",
    area: "Jumeirah",
    community: "Jumeirah 2",
    type: "villa",
    bedrooms: 4,
    sqft: 3520,
    originalPrice: 320000,
    currentPrice: 219840,
    daysOnMarket: 31,
    droppedYesterday: true,
    expatArea: true,
    familyFriendly: true,
  },
  {
    id: "jumeirah-2",
    title: "2BR | Jumeirah | Low-Rise Coastal Unit",
    area: "Jumeirah",
    community: "La Mer Residences",
    type: "apartment",
    bedrooms: 2,
    sqft: 1285,
    originalPrice: 212000,
    currentPrice: 188000,
    daysOnMarket: 14,
    droppedYesterday: false,
    expatArea: true,
  },
  {
    id: "jumeirah-3",
    title: "3BR Villa | Jumeirah | Private Terrace",
    area: "Jumeirah",
    community: "Jumeirah 1",
    type: "villa",
    bedrooms: 3,
    sqft: 2870,
    originalPrice: 295000,
    currentPrice: 265000,
    daysOnMarket: 17,
    droppedYesterday: true,
    expatArea: true,
    familyFriendly: true,
  },
];

export const listings = listingConfigs.map(createListing);
export const areaLookup = areaMeta;
export const listingScanVolume = 14633;
export const liveWatchers = 50567;

export function getAreaSummaries(inputListings = listings) {
  return Object.entries(areaMeta)
    .map(([area, details]) => {
      const areaListings = inputListings.filter((listing) => listing.area === area);
      const dropCount = areaListings.length;
      const avgDropPercent =
        dropCount === 0
          ? 0
          : areaListings.reduce((sum, listing) => sum + listing.dropPercent, 0) / dropCount;
      const avgDropAmount =
        dropCount === 0
          ? 0
          : areaListings.reduce((sum, listing) => sum + listing.dropAmount, 0) / dropCount;

      return {
        area,
        label: details.label,
        community: details.community,
        lat: details.lat,
        lng: details.lng,
        sparkline: details.sparkline,
        dropCount,
        avgDropPercent: Number(avgDropPercent.toFixed(1)),
        avgDropAmount: Math.round(avgDropAmount),
      };
    })
    .sort((left, right) => {
      if (right.dropCount !== left.dropCount) {
        return right.dropCount - left.dropCount;
      }

      return right.avgDropPercent - left.avgDropPercent;
    });
}

export function getDashboardStats(inputListings = listings) {
  const sortedByPercent = [...inputListings].sort((left, right) => right.dropPercent - left.dropPercent);
  const sortedByAmount = [...inputListings].sort((left, right) => right.dropAmount - left.dropAmount);
  const totalSavings = inputListings.reduce((sum, listing) => sum + listing.dropAmount, 0);

  return {
    totalDrops: inputListings.length,
    biggestDrop: sortedByPercent[0],
    biggestAmountDrop: sortedByAmount[0],
    totalSavings,
    averageDrop:
      inputListings.reduce((sum, listing) => sum + listing.dropPercent, 0) / Math.max(inputListings.length, 1),
  };
}
